spring.application.name=drinkbros-backend
spring.datasource.url=jdbc:mysql://localhost:3306/drinkbros
spring.datasource.username=root
spring.dataSource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000
spring.jackson.property-naming-strategy=SNAKE_CASE

server.servlet.context-path=/
swagger.username=drinkbro
swagger.password=drinkbro

mercadoPago.url=${MERCADOPAGO_URL:https://api.mercadopago.com}
mercadopago.connect.timeout=10
mercadopago.read.timeout=60
mercadopago.client-secret=60
mercadopago.client-id=60

logging.level.okhttp3=${RETROFIT_LOG:debug}